algoritmo "CONTADOR"
// Função :
// Autor :
// Data : 29/10/2021
// Seção de Declarações 
var

    salto, valor, contador: inteiro

inicio
       contador <- 0
       escreva ("Quer contar até quanto?" )
       leia (valor)
       escreva ("Salto de quanto? " )
       leia (salto)
       enquanto (contador <= valor) faca
       escreval (contador)
       contador <- contador + salto
       fimenquanto
// Seção de Comandos 
fimalgoritmo
